const assert = require('node:assert/strict');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1180, height: 820 }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.GAME_URL || 'http://127.0.0.1:8765/');
  await page.evaluate(async () => { window.inspectGame = (await import('./game.js')).snapshot; });
  const snapshot = () => page.evaluate(() => window.inspectGame());
  const waitState = state => page.waitForFunction(state => window.inspectGame().state === state, state, { timeout: 25000 });
  await page.waitForFunction(() => document.querySelector('canvas').dataset.offline === 'ready');
  await waitState('PLAYING');
  const initial = await snapshot();
  assert.equal(initial.actorX, 65);
  assert.equal(initial.guideMarker.opacity,0,'no guide cue during the puzzle');
  await page.waitForTimeout(300);
  assert.equal((await snapshot()).frame, initial.frame, 'walk animation stops at rest');
  const point = async (x,y) => {
    const r = await page.locator('canvas').boundingBox();
    return { x:r.x+x*r.width/1280, y:r.y+y*r.height/800 };
  };
  const drag = async (from,to) => {
    const a=await point(...from),b=await point(...to);
    await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();
  };
  const tap = async (x,y) => {const p=await point(x,y);await page.mouse.click(p.x,p.y);};
  // Misses return home, including a drop on a different shape's socket.
  await drag([465,490],[640,265]);await page.waitForTimeout(450);
  assert.equal((await snapshot()).pieces[0].placed,false);
  assert.equal((await snapshot()).pieces[0].x,465);
  // Preserve the initial touch offset rather than centering under the pointer.
  let p=await point(490,500);await page.mouse.move(p.x,p.y);await page.mouse.down();
  p=await point(590,450);await page.mouse.move(p.x,p.y);
  assert.ok(Math.abs((await snapshot()).pieces[0].x-565)<1);
  await page.mouse.up();await page.waitForTimeout(450);
  // Real browser touch events: ignore a second finger; cancel safely.
  const session = await context.newCDPSession(page);
  const a=await point(465,490),b=await point(635,490);
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1},{...b,id:2}]});
  assert.equal((await snapshot()).active,'circle');
  await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
  await page.waitForTimeout(450);
  assert.equal((await snapshot()).active,null);
  assert.equal((await snapshot()).pieces[0].x,465);
  // Forgiving snap accepts a release 85 logical pixels from the socket centre.
  await drag([465,490],[520,265]);await page.waitForTimeout(300);
  assert.equal((await snapshot()).pieces[0].x,435);
  await drag([435,265],[200,200]);
  assert.equal((await snapshot()).pieces[0].placed,true);
  await drag([635,490],[640,265]);
  await drag([805,490],[845,265]);
  await drag([975,490],[1050,265]);
  await waitState('COMPLETE');
  await page.waitForTimeout(350);
  await page.screenshot({path:path.join(__dirname,'complete.png')});
  await waitState('GUIDE_TO_EXIT');
  assert.equal((await snapshot()).open,true);
  const waiting=await snapshot();
  assert.equal(waiting.guideMarker.opacity,0,'no guide cue before touching');
  await page.waitForTimeout(650);
  assert.equal((await snapshot()).actorX,waiting.actorX,'completion must wait for the child');
  assert.equal((await snapshot()).frame,waiting.frame);
  await tap(1050,265);await tap(100,600);await page.waitForTimeout(200);
  assert.equal((await snapshot()).actorX,65,'upper puzzle area and backwards targets do not move the actor');
  await tap(500,600);
  await page.waitForTimeout(180);
  let guided=await snapshot();
  assert.ok(guided.actorX>65&&guided.actorX<100,`walks toward touch instead of teleporting: ${JSON.stringify({guided,errors})}`);
  assert.equal(guided.walking,true);
  assert.equal(guided.guiding,false,'released tap still leaves a target to finish');
  await page.waitForFunction(()=>!window.inspectGame().walking&&window.inspectGame().actorX>200);
  guided=await snapshot();assert.ok(Math.abs(guided.actorX-234.5)<1);
  assert.equal(guided.guideMarker.opacity,0,'released guide marker fades away');
  await page.waitForTimeout(250);assert.equal((await snapshot()).frame,guided.frame,'frame freezes at a local guide target');
  const frozenPieces=guided.pieces;
  p=await point(600,600);await page.mouse.move(p.x,p.y);await page.mouse.down();
  assert.equal((await snapshot()).guideMarker.opacity,1);
  assert.ok(Math.abs((await snapshot()).guideMarker.x-600)<1);
  await page.waitForTimeout(180);const beforeForward=(await snapshot()).actorX;
  p=await point(800,410);await page.mouse.move(p.x,p.y);await page.waitForTimeout(180);
  assert.equal((await snapshot()).guideMarker.opacity,1);
  assert.ok(Math.abs((await snapshot()).guideMarker.x-800)<1,'visible cue follows the drag target');
  await page.screenshot({path:path.join(__dirname,'guide-marker.png')});
  assert.ok((await snapshot()).actorX>beforeForward,'continued drag extends forward walking');
  const beforeReverse=(await snapshot()).actorX;
  p=await point(100,100);await page.mouse.move(p.x,p.y);await page.mouse.up();
  await page.waitForTimeout(180);
  assert.ok((await snapshot()).actorX>=beforeReverse,'reverse and vertical drags cannot pull it backwards');
  assert.equal((await snapshot()).walking,false);
  assert.deepEqual((await snapshot()).pieces,frozenPieces,'shapes stay locked during guiding');
  // Real multi-touch during guiding: the second pointer must not replace the target.
  const ga=await point(700,600),gb=await point(1200,600);
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...ga,id:1}]});
  const target=(await snapshot()).guideTargetX;
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...ga,id:1},{...gb,id:2}]});
  assert.equal((await snapshot()).guideTargetX,target);
  await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
  await page.waitForTimeout(150);const cancelled=await snapshot();
  assert.equal(cancelled.guiding,false);assert.equal(cancelled.walking,false);
  assert.equal(cancelled.guideMarker.opacity,0,'cancel removes the feedback layer');
  await page.waitForTimeout(150);assert.equal((await snapshot()).actorX,cancelled.actorX);
  // Losing focus clears the held pointer and pending target, then a new touch works.
  await tap(800,600);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
  await page.waitForTimeout(150);assert.equal((await snapshot()).walking,false);
  await page.screenshot({path:path.join(__dirname,'guiding.png')});
  // Regression: a touch at the FRONT of the doorway used to stop short of handoff.
  const door=await point(1102,600);
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...door,id:1}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await waitState('EXITING');
  const handoff=await snapshot();
  assert.ok(handoff.actorX>=808.5&&handoff.actorX<840,'near-door touch hands off without precision');
  assert.equal(handoff.guiding,false);
  assert.equal(handoff.guideMarker.opacity,0,'cue hides throughout automatic exit');
  assert.equal(handoff.walking,true);
  await tap(100,600);await tap(640,265);await page.waitForTimeout(320);
  const through=await snapshot();
  assert.equal(through.state,'EXITING');assert.equal(through.walking,true);
  assert.ok(through.actorX>handoff.actorX,'keeps moving after finger release, ignoring exit-phase input');
  assert.notEqual(through.frame,handoff.frame,'walk animation continues through handoff');
  await page.waitForTimeout(1000);
  await page.screenshot({path:path.join(__dirname,'entering-door.png')});
  await page.waitForFunction(()=>window.inspectGame().actorHidden&&window.inspectGame().state==='EXITING');
  assert.equal((await snapshot()).guideMarker.opacity,0);
  await page.screenshot({path:path.join(__dirname,'hidden-door.png')});
  await waitState('TRANSITIONING');assert.ok((await snapshot()).actorX>=1222);
  assert.equal((await snapshot()).actorHidden,true,'reset starts only after fully clearing the mask');
  await waitState('ENTERING');assert.equal((await snapshot()).pieces.filter(p=>p.placed).length,0);
  await waitState('PLAYING');
  assert.equal((await snapshot()).cycle,2);
  assert.equal((await snapshot()).levelId,2,'full exit advances to the next level');
  assert.equal((await snapshot()).guiding,false);
  assert.equal((await snapshot()).guideTargetX,65,'reset clears the previous target');
  assert.equal((await snapshot()).guideMarker.opacity,0);
  await page.screenshot({path:path.join(__dirname,'playing.png')});
  // Check a different landscape aspect ratio, then drag with actual touch input.
  await page.setViewportSize({width:1024,height:768});
  await page.waitForFunction(()=>{const r=document.querySelector('canvas').getBoundingClientRect();return Math.abs(r.width/r.height-1.6)<.01;});
  const r=await page.locator('canvas').boundingBox();assert.ok(Math.abs(r.width/r.height-1.6)<.01);
  const ta=await point(465,490),tb=await point(435,265);
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...ta,id:1}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...tb,id:1}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.waitForTimeout(300);assert.equal((await snapshot()).pieces[0].placed,true);
  // A fresh offline navigation must load every dependency from the service worker.
  await context.setOffline(true);await page.reload();
  await page.evaluate(async () => {window.inspectGame=(await import('./game.js')).snapshot;});
  await waitState('PLAYING');
  await drag([465,490],[435,265]);await drag([635,490],[640,265]);await drag([805,490],[845,265]);await drag([975,490],[1050,265]);
  await waitState('COMPLETE');await waitState('GUIDE_TO_EXIT');
  await page.waitForTimeout(300);assert.equal((await snapshot()).actorX,65);
  // A near-door target also works offline, with no requirement to reach its centre.
  await tap(1080,620);
  await waitState('EXITING');await waitState('TRANSITIONING');await waitState('ENTERING');
  assert.deepEqual(errors,[]);
  console.log('PASS: original shape interactions; visible guide tracks the finger, fades and clears; rightward following; multi-touch/cancellation; front-edge and near-door handoff; uninterrupted automatic walk animation; fully hidden before reset; tablet resize; offline guided loop. No browser errors.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
